COMMENT !

Include procedures definitions to use with Library64.lib

Version 1.0, 13/11/2021

Bug fixes:

!

externdef GetCharA:PROC
externdef GetCharW:PROC
externdef GetStdHandleIn:PROC
externdef GetStdHandleOut:PROC
externdef StructInit:PROC
externdef StrCompareA:PROC
externdef StrCompareW:PROC
externdef StrCopyA:PROC
externdef StrCopyW:PROC
externdef StrLengthA:PROC
externdef StrLengthW:PROC
externdef WaitKey:PROC
